services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - .:/var/www/site
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - "8080:80"
    links:
      - db
  db:
    container_name: mysql
    image: "mysql:5.6"
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: phpapptest 
      MYSQL_DATABASE: thanksforallthefish
